const $=id=>document.getElementById(id);const NS='http://www.w3.org/2000/svg';
function text(v){return v===null||v===undefined?'—':String(v)}
function gap(v,unit){return v>=0?`还差 ${v}${unit}`:`超出 ${Math.abs(v)}${unit}`}
function status(day){if(!day.foods.length)return'未记录饮食';if(day.protein_g<120)return'蛋白不足';if(day.calories>1900)return'热量偏高';return'执行良好'}
function renderToday(d){$('today-date').textContent=d.date;$('calories').textContent=`${d.calories} kcal`;$('protein').textContent=`${d.protein_g}g`;$('calorie-gap').textContent=`/ 1800 kcal · ${gap(d.calorie_gap,' kcal')}`;$('protein-gap').textContent=`/ 130g · ${gap(d.protein_gap,'g')}`;$('exercise').textContent=d.exercise_status;$('judgement').textContent=d.judgement;const box=$('meals');box.replaceChildren();for(const [label,entries] of Object.entries(d.meals)){if(!entries.length)continue;const card=document.createElement('article');card.className='meal';const c=entries.reduce((n,e)=>n+e.estimated_total_calories,0),p=entries.reduce((n,e)=>n+e.estimated_total_protein_g,0);const head=document.createElement('header'),title=document.createElement('strong'),sum=document.createElement('span');title.textContent=label;sum.textContent=`${c} kcal · ${p}g`;head.append(title,sum);const list=document.createElement('ul');entries.flatMap(e=>e.items).forEach(i=>{const li=document.createElement('li');const score=i.estimated_calories?`${(i.estimated_protein_g/i.estimated_calories*100).toFixed(1)}g/100kcal`:'—';li.textContent=`${i.name} ${i.quantity} · ${i.estimated_calories} kcal · ${i.estimated_protein_g}g · ${score}`;list.append(li)});card.append(head,list);box.append(card)}if(!d.foods.length){const empty=document.createElement('div');empty.className='empty';empty.textContent='今天还没有饮食记录';box.append(empty)}}
function renderTable(days){const body=$('week-table');body.replaceChildren();days.forEach(d=>{const tr=document.createElement('tr');[d.date,d.foods.length?d.calories:'未记录',d.foods.length?`${d.protein_g}g`:'未记录',d.exercise_status,d.weight?`${d.weight.value}kg`:'未记录',status(d)].forEach(v=>{const td=document.createElement('td');td.textContent=text(v);tr.append(td)});body.append(tr)})}
function svgEl(name,attrs={}){const el=document.createElementNS(NS,name);for(const[k,v]of Object.entries(attrs))el.setAttribute(k,v);return el}
function chart(id,values,color,reference=null){const svg=$(id);svg.replaceChildren();const W=640,H=220,pad=34;const present=values.filter(v=>v.value!==null&&v.value!==undefined).map(v=>Number(v.value));const all=reference===null?present:present.concat(reference);if(!present.length){const t=svgEl('text',{x:W/2,y:H/2,'text-anchor':'middle',fill:'#666','font-size':'13'});t.textContent='暂无记录';svg.append(t);return}let min=Math.min(...all),max=Math.max(...all);if(min===max){min-=1;max+=1}const x=i=>pad+i*(W-pad*2)/Math.max(1,values.length-1),y=v=>H-pad-(v-min)*(H-pad*2)/(max-min);if(reference!==null){svg.append(svgEl('line',{x1:pad,x2:W-pad,y1:y(reference),y2:y(reference),stroke:'#666','stroke-dasharray':'5 5'}))}let segment=[];const flush=()=>{if(!segment.length)return;const points=segment.map(p=>`${x(p.i)},${y(p.value)}`).join(' ');svg.append(svgEl('polyline',{points,fill:'none',stroke:color,'stroke-width':'3','stroke-linecap':'round','stroke-linejoin':'round'}));segment=[]};values.forEach((v,i)=>{if(v.value===null||v.value===undefined){flush();return}segment.push({i,value:Number(v.value)});svg.append(svgEl('circle',{cx:x(i),cy:y(v.value),r:'3',fill:color}))});flush();const lo=svgEl('text',{x:4,y:H-pad+4,fill:'#666','font-size':'10'});lo.textContent=min.toFixed(1);const hi=svgEl('text',{x:4,y:pad+4,fill:'#666','font-size':'10'});hi.textContent=max.toFixed(1);svg.append(lo,hi)}
function renderCharts(trend,settings){chart('calorie-chart',trend.days.map(d=>({value:d.foods.length?d.calories:null})), '#f472b6',settings.calorie_target_kcal);chart('protein-chart',trend.days.map(d=>({value:d.foods.length?d.protein_g:null})), '#53bdeb',settings.protein_target_g);chart('weight-chart',trend.weight_7d_average.map(d=>({value:d.value})), '#e0e0e0')}
async function load(){const statusBox=$('status');statusBox.className='status';statusBox.textContent='正在读取后端汇总…';try{const response=await fetch('/api/dashboard',{cache:'no-store'});const data=await response.json();if(!data.ok)throw new Error(data.error||'数据生成失败');renderToday(data.today);renderTable(data.days);renderCharts(data.trend,data.settings);$('program-length').textContent=`周期：${data.settings.program_weeks} 周`;$('updated').textContent=`数据最后更新时间：${data.generated_at}`;$('source').textContent=`当前数据源文件：${data.source_files.join(', ')}`;statusBox.textContent='数据来自 backend/service.py 对 JSONL 有效事件的实时投影。'}catch(error){statusBox.className='status error';statusBox.textContent=`生成失败/数据损坏状态：${error.message}`;$('updated').textContent='数据最后更新时间：读取失败';$('source').textContent='当前数据源文件：无法安全确认'}}
$('refresh').addEventListener('click',load);load();
