const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
function text(v){return v===null||v===undefined?'—':String(v)}
function gap(v,unit){return v>=0?`还差 ${v}${unit}`:`超出 ${Math.abs(v)}${unit}`}
function status(day){if(!day.foods.length)return'未记录饮食';if(day.protein_g<day.targets.protein_g)return'蛋白不足';if(day.calories>day.targets.calories)return'热量偏高';return'执行良好'}
function renderToday(d){$('today-date').textContent=d.date;$('calories').textContent=`${d.calories} kcal`;$('protein').textContent=`${d.protein_g}g`;$('calorie-gap').textContent=`/ ${d.targets.calories} kcal · ${gap(d.calorie_gap,' kcal')}`;$('protein-gap').textContent=`/ ${d.targets.protein_g}g · ${gap(d.protein_gap,'g')}`;$('exercise').textContent=d.exercise_status;$('judgement').textContent=d.judgement;const box=$('meals');box.replaceChildren();for(const [label,entries] of Object.entries(d.meals)){if(!entries.length)continue;const card=document.createElement('article');card.className='meal';const c=entries.reduce((n,e)=>n+e.estimated_total_calories,0),p=entries.reduce((n,e)=>n+e.estimated_total_protein_g,0),head=document.createElement('header'),title=document.createElement('strong'),sum=document.createElement('span');title.textContent=label;sum.textContent=`${c} kcal · ${p}g`;head.append(title,sum);const list=document.createElement('ul');entries.flatMap(e=>e.items).forEach(i=>{const li=document.createElement('li'),score=i.estimated_calories?`${(i.estimated_protein_g/i.estimated_calories*100).toFixed(1)}g/100kcal`:'—';li.textContent=`${i.name} ${i.quantity} · ${i.estimated_calories} kcal · ${i.estimated_protein_g}g · ${score}`;list.append(li)});card.append(head,list);box.append(card)}if(!d.foods.length){const empty=document.createElement('div');empty.className='empty';empty.textContent='今天还没有饮食记录';box.append(empty)}}
function renderTable(days){const body=$('week-table');body.replaceChildren();days.forEach(d=>{const tr=document.createElement('tr');[d.date,d.foods.length?d.calories:'未记录',d.foods.length?`${d.protein_g}g`:'未记录',d.exercise_status,d.weight?`${d.weight.value}kg`:'未记录',status(d)].forEach(v=>{const td=document.createElement('td');td.textContent=text(v);tr.append(td)});body.append(tr)})}
function svgEl(name,attrs={}){const el=document.createElementNS(NS,name);for(const[k,v]of Object.entries(attrs))el.setAttribute(k,v);return el}
function chart(id,values,color,reference=null){const svg=$(id);svg.replaceChildren();const W=640,H=220,pad=34,present=values.filter(v=>v.value!==null&&v.value!==undefined).map(v=>Number(v.value)),all=reference===null?present:present.concat(reference);if(!present.length){const t=svgEl('text',{x:W/2,y:H/2,'text-anchor':'middle',fill:'#666','font-size':'13'});t.textContent='暂无记录';svg.append(t);return}let min=Math.min(...all),max=Math.max(...all);if(min===max){min-=1;max+=1}const x=i=>pad+i*(W-pad*2)/Math.max(1,values.length-1),y=v=>H-pad-(v-min)*(H-pad*2)/(max-min);if(reference!==null)svg.append(svgEl('line',{x1:pad,x2:W-pad,y1:y(reference),y2:y(reference),stroke:'#666','stroke-dasharray':'5 5'}));let segment=[];const flush=()=>{if(!segment.length)return;svg.append(svgEl('polyline',{points:segment.map(p=>`${x(p.i)},${y(p.value)}`).join(' '),fill:'none',stroke:color,'stroke-width':'3','stroke-linecap':'round','stroke-linejoin':'round'}));segment=[]};values.forEach((v,i)=>{if(v.value===null||v.value===undefined){flush();return}segment.push({i,value:Number(v.value)});svg.append(svgEl('circle',{cx:x(i),cy:y(v.value),r:'3',fill:color}))});flush()}
function renderCharts(trend,settings){chart('calorie-chart',trend.days.map(d=>({value:d.foods.length?d.calories:null})),'#f472b6',settings.calorie_target_kcal);chart('protein-chart',trend.days.map(d=>({value:d.foods.length?d.protein_g:null})),'#53bdeb',settings.protein_target_g);chart('weight-chart',trend.weight_7d_average.map(d=>({value:d.value})),'#e0e0e0')}
function showOnboarding(data){$('onboarding').hidden=false;$('dashboard').hidden=true;$('edit-profile').hidden=true;$('program-length').textContent='需要完成本地档案设置';$('status').textContent=data.profile_status?.legacy_config_detected?'检测到旧 config.json；可迁移目标值，但仍需完成档案设置。':'填写后才会显示你的仪表盘。'}
function showDashboard(data){$('onboarding').hidden=true;$('dashboard').hidden=false;$('edit-profile').hidden=false;const p=data.profile.profile,plan=data.profile.plan;$('program-length').textContent=`${p.current_weight_kg} kg → ${p.target_weight_kg} kg · ${plan.start_date} 至 ${plan.end_date} · ${plan.program_weeks} 周`;renderToday(data.today);renderTable(data.days);renderCharts(data.trend,data.settings);$('updated').textContent=`数据最后更新时间：${data.generated_at}`;$('source').textContent=`当前数据源文件：${data.source_files.join(', ')}`;$('status').textContent='数据由 backend/service.py 对 JSONL 有效事件实时投影。'}
function numberOrNull(form,name){const v=form.elements[name].value.trim();return v===''?null:Number(v)}
function setMode(){const form=$('profile-form'),weeks=form.elements.program_weeks,date=form.elements.end_date,isWeeks=form.elements.plan_mode.value==='weeks';weeks.disabled=!isWeeks;date.disabled=isWeeks}
async function saveProfile(event){event.preventDefault();const form=event.currentTarget,mode=form.elements.plan_mode.value,plan={timezone:'Asia/Shanghai'};if(mode==='weeks')plan.program_weeks=numberOrNull(form,'program_weeks');else plan.end_date=form.elements.end_date.value;['calorie_target_kcal','protein_target_g'].forEach(k=>{const v=numberOrNull(form,k);if(v!==null)plan[k]=v});const payload={profile:{height_cm:numberOrNull(form,'height_cm'),current_weight_kg:numberOrNull(form,'current_weight_kg'),target_weight_kg:numberOrNull(form,'target_weight_kg'),age:numberOrNull(form,'age'),sex:form.elements.sex.value,activity_level:form.elements.activity_level.value||null,weekly_training_frequency:numberOrNull(form,'weekly_training_frequency')},plan};try{$('status').textContent='正在安全保存本地档案…';const response=await fetch('/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||'保存失败');if(data.warning)$('status').textContent='已保存，但目标变化较快；请根据身体状态放慢计划。';await load()}catch(error){$('status').className='status error';$('status').textContent=`档案未保存：${error.message}`}}
async function load(){const statusBox=$('status');statusBox.className='status';statusBox.textContent='正在读取后端汇总…';try{const response=await fetch('/api/dashboard',{cache:'no-store'}),data=await response.json();if(!data.ok)throw new Error(data.error||'数据生成失败');if(!data.configured){showOnboarding(data);return}showDashboard(data)}catch(error){statusBox.className='status error';statusBox.textContent=`生成失败/档案损坏状态：${error.message}`;$('onboarding').hidden=true;$('dashboard').hidden=true}}
$('refresh').addEventListener('click',load);$('edit-profile').addEventListener('click',()=>{$('onboarding').hidden=false;$('dashboard').hidden=true;$('edit-profile').hidden=true;$('status').textContent='修改目标不会改写历史 JSONL 记录。'});$('profile-form').addEventListener('submit',saveProfile);document.querySelectorAll('input[name="plan_mode"]').forEach(el=>el.addEventListener('change',setMode));setMode();load();
